language: python

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda create --yes --name test python=$TRAVIS_PYTHON_VERSION
  - conda env update --file conda.yml --name test
  - source activate test

jobs:
  include:
    - stage: test
      os: linux
      dist: xenial
      python: 3.6.9
      script:
        - pytest -x tests/
    - stage: coverage
      os: linux
      dist: xenial
      python: 3.6.9
      script:
        - pytest --cov=src tests/
        - codecov
