language: python

matrix:
  include:
    - os: linux
      dist: xenial
      python: 3.6.9

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda create --yes --name test python=$TRAVIS_PYTHON_VERSION
  - conda env update --file conda.yml --name test
  - source activate test

script:
  - pytest -x tests/